apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pets
spec:
  destination:
    name: ''
    namespace: pets
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/aks-store-demo
    repoURL: 'https://github.com/pauldotyu/aks-store-demo'
    targetRevision: bigbertha
    helm:
      parameters:
        - name: aiService.image.repository
          value: ghcr.io/pauldotyu/aks-store-demo/ai-service
        - name: makelineService.image.repository
          value: ghcr.io/pauldotyu/aks-store-demo/makeline-service
        - name: orderService.image.repository
          value: ghcr.io/pauldotyu/aks-store-demo/order-service
        - name: productService.image.repository
          value: ghcr.io/pauldotyu/aks-store-demo/product-service
        - name: storeAdmin.image.repository
          value: ghcr.io/pauldotyu/aks-store-demo/store-admin
        - name: storeAdmin.serviceType
          value: ClusterIP
        - name: storeFront.image.repository
          value: ghcr.io/pauldotyu/aks-store-demo/store-front
        - name: storeFront.serviceType
          value: ClusterIP
        - name: virtualCustomer.image.repository
          value: ghcr.io/pauldotyu/aks-store-demo/virtual-customer
        - name: virtualWorker.image.repository
          value: ghcr.io/pauldotyu/aks-store-demo/virtual-worker
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
