apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
namespace: pets
images:
- name: ghcr.io/azure-samples/aks-store-demo/makeline-service
  newName: ghcr.io/pauldotyu/aks-store-demo/makeline-service
  newTag: 1.2.0
- name: ghcr.io/azure-samples/aks-store-demo/order-service
  newName: ghcr.io/pauldotyu/aks-store-demo/order-service
  newTag: 1.2.0
- name: ghcr.io/azure-samples/aks-store-demo/product-service
  newName: ghcr.io/pauldotyu/aks-store-demo/product-service
  newTag: 1.2.0
- name: ghcr.io/azure-samples/aks-store-demo/store-admin
  newName: ghcr.io/pauldotyu/aks-store-demo/store-admin
  newTag: 1.2.0
- name: ghcr.io/azure-samples/aks-store-demo/store-front
  newName: ghcr.io/pauldotyu/aks-store-demo/store-front
  newTag: 1.2.0
- name: ghcr.io/azure-samples/aks-store-demo/virtual-customer
  newName: ghcr.io/pauldotyu/aks-store-demo/virtual-customer
  newTag: 1.2.0
- name: ghcr.io/azure-samples/aks-store-demo/virtual-worker
  newName: ghcr.io/pauldotyu/aks-store-demo/virtual-worker
  newTag: 1.2.0
