name: release-helm-chart

on:
  push:
    branches:
      - 'main'
    paths:
      - 'charts/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-container-image:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
  
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
          
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}

      # - name: Set environment variables
      #   id: set-variables
      #   run: |
      #     echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      # - name: Env variable output
      #   id: test-variables
      #   run: |
      #     echo ${{ steps.set-variables.outputs.REPOSITORY }}

      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ github.token }}

      # - name: Package and push helm chart
      #   run: |
      #     helm package ./charts/aks-store-demo --version ${{ steps.set-variables.outputs.VERSION }}
      #     helm push ./aks-store-demo-chart-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ steps.set-variables.outputs.REPOSITORY }}/charts